import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const TermsOfService = () => (
  <div className="min-h-screen bg-background">
    <div className="max-w-[720px] mx-auto px-4 py-8 space-y-8">
      <div className="flex items-center justify-between">
        <Button variant="ghost" asChild className="gap-2">
          <Link to="/"><ArrowLeft className="h-4 w-4" /> Back to Home</Link>
        </Button>
        <Link to="/" className="flex items-center gap-2">
          <img src="/favicon.ico" alt="VidMind" className="h-6 w-6" />
          <span className="text-lg font-bold text-primary" style={{ fontFamily: "'DM Sans', sans-serif" }}>VidMind</span>
        </Link>
      </div>

      <h1 className="text-3xl font-bold text-foreground">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last updated: March 2025</p>

      <div className="space-y-6 text-muted-foreground leading-relaxed" style={{ fontFamily: "'DM Sans', sans-serif" }}>
        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">1. Acceptance of Terms</h2>
          <p>By using VidMind, you agree to these Terms of Service. If you do not agree, please do not use the service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">2. Description of Service</h2>
          <p>VidMind is an AI-powered YouTube video summarization tool. Users can paste video transcripts to receive structured summaries, save notes, and organize learning content.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">3. User Accounts</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>You must provide accurate information when creating an account</li>
            <li>You are responsible for maintaining the security of your account</li>
            <li>You must be at least 13 years old to use VidMind</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">4. Acceptable Use</h2>
          <p>You agree NOT to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Submit illegal, harmful, or abusive content for summarization</li>
            <li>Attempt to reverse engineer or hack the service</li>
            <li>Use VidMind to violate YouTube's Terms of Service</li>
            <li>Share your account credentials with others</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">5. Intellectual Property</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>Summaries generated by VidMind are for your personal use</li>
            <li>You retain ownership of notes you create</li>
            <li>VidMind's branding, design, and code are owned by VidMind</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">6. Free and Pro Plans</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>Free plan users get 10 summaries per month</li>
            <li>Pro plan users get unlimited summaries</li>
            <li>We reserve the right to change pricing with 30 days notice</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">7. Disclaimer</h2>
          <p>VidMind is provided "as is" without warranty of any kind. We are not responsible for the accuracy of AI-generated summaries. Always verify important information from the original source.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">8. Limitation of Liability</h2>
          <p>VidMind shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">9. Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">10. Contact</h2>
          <p>For questions about these terms: <a href="mailto:legal@vidmind.app" className="text-primary hover:underline">legal@vidmind.app</a></p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-2">11. Governing Law</h2>
          <p>These terms are governed by applicable laws. Disputes will be resolved through good faith negotiation.</p>
        </section>
      </div>
    </div>
  </div>
);

export default TermsOfService;
